version: '3.8'

services:
  db:
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: payments
      MYSQL_USER: rafael
      MYSQL_PASSWORD: senha123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: